apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrixhub.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrixhub.apiserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "matrixhub.apiserver.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matrixhub.apiserver.labels" . | nindent 8 }}
        {{- include "matrixhub.apiserver.podLabels" . | nindent 8 }}
    spec:
      initContainers:
        {{- if .Values.global.storage.apiserver.builtIn }}
        - name: check-db-ready
          image: {{ .Values.global.busybox.image.repository }}:{{ .Values.global.busybox.image.tag }}
          imagePullPolicy: {{ .Values.global.busybox.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              echo 'Waiting for DataBase to become ready...'
              until printf "." && nc -z -w 2 {{ include "matrixhub.fullname" . }}-mysql 3306; do
                sleep 2;
              done;
              echo 'database OK âœ“'
        {{- end }}
      {{- include "matrixhub.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ include "matrixhub.fullname" . }}-apiserver
          image: {{ include "matrixhub.image" . }}
          imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/matrixhub/config.yaml
              name: {{ include "matrixhub.fullname" . }}-apiserver-config
              subPath: config.yaml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - name: http
              containerPort: {{ .Values.apiserver.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.apiserver.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.apiserver.port }}
          command:
            - /usr/local/bin/matrixhub
            - apiserver
            - -c
            - /etc/matrixhub/config.yaml
          env:
            - name: MATRIXHUB_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrixhub.fullname" . }}-secret
                  key: matrixhub.dsn
      volumes:
        - name: {{ include "matrixhub.fullname" . }}-apiserver-config
          configMap:
            name: {{ include "matrixhub.fullname" . }}-apiserver-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
