apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrixhub.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrixhub.apiserver.labels" . | nindent 4 }}
  {{- with .Values.apiserver.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.apiserver.service.type "NodePort") (eq .Values.apiserver.service.type "LoadBalancer")) (not (empty .Values.apiserver.service.nodePort)) }}
      nodePort: {{ .Values.apiserver.service.nodePort }}
      {{- else if eq .Values.apiserver.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "matrixhub.apiserver.labels" . | nindent 4 }}
