apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrixhub.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrixhub.apiserver.labels" . | nindent 4 }}