apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrixhub.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrixhub.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.global.storage.apiserver.builtIn .Values.mysql.rootPassword }}
  matrixhub.dsn: {{ include "matrixhub.database.dsn" . | b64enc | quote }}
  {{- else }}
  matrixhub.dsn: {{ .Values.apiserver.database.dsn | b64enc | quote }}
  {{- end }}
  {{- if and .Values.global.storage.apiserver.builtIn .Values.mysql.rootPassword }}
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  {{- end }}